const buttonData = [
  {
    id: 1,
    name: "Button 1",
    number: "button_1",
    style: {
      backgroundColor: "#ea4c89",
      borderRadius: "8px",
      borderStyle: "none",
      boxSizing: "border-box",
      color: "#ffffff",
      cursor: "pointer",
      display: "inline-block",
      fontFamily:
        "Haas Grot Text R Web, Helvetica Neue, Helvetica, Arial, sans-serif",
      fontSize: "14px",
      fontWeight: "500",
      height: "40px",
      lineHeight: "20px",
      listStyle: "none",
      margin: "0",
      outline: "none",
      padding: "10px 16px",
      position: "relative",
      textAlign: "center",
      textDecoration: "none",
      transition: "color 100ms",
      verticalAlign: "baseline",
      userSelect: "none",
      touchAction: "manipulation",
    },
  },
  {
    id: 2,
    name: "Button 2",
    number: "button_2",
    style: {
      backgroundColor: "rgba(51, 51, 51, 0.05)",
      borderRadius: "8px",
      borderWidth: "0",
      borderStyle: "none",
      boxSizing: "border-box",
      color: "#333333",
      cursor: "pointer",
      display: "inline-block",
      fontFamily:
        "Haas Grot Text R Web, Helvetica Neue, Helvetica, Arial, sans-serif",
      fontSize: "14px",
      fontWeight: "500",
      height: "40px",
      lineHeight: "20px",
      listStyle: "none",
      margin: "0",
      outline: "none",
      padding: "10px 12px",
      position: "relative",
      textAlign: "center",
      textDecoration: "none",
      transition: "all 200ms",
      whiteSpace: "nowrap",
      verticalAlign: "baseline",
      userSelect: "none",
      touchAction: "manipulation",
    },
  },
  {
    id: 3,
    name: "Button 2",
    number: "button_2",
    style: {
      backgroundColor: "rgba(51, 51, 51, 0.05)",
      borderRadius: "8px",
      borderWidth: "0",
      borderStyle: "none",
      boxSizing: "border-box",
      color: "#333333",
      cursor: "pointer",
      display: "inline-block",
      fontFamily:
        "Haas Grot Text R Web, Helvetica Neue, Helvetica, Arial, sans-serif",
      fontSize: "14px",
      fontWeight: "500",
      height: "40px",
      lineHeight: "20px",
      listStyle: "none",
      margin: "0",
      outline: "none",
      padding: "10px 12px",
      position: "relative",
      textAlign: "center",
      textDecoration: "none",
      transition: "all 200ms",
      whiteSpace: "nowrap",
      verticalAlign: "baseline",
      userSelect: "none",
      touchAction: "manipulation",
    },
  },
];
export default buttonData;
