const shapesData = [
  {
    id: 1,
    name: "Triangle Up",
    number: "#1",
    style: {
      width: "0",
      height: "0",
      borderLeft: "25px solid transparent",
      borderRight: "25px solid transparent",
      borderBottom: "50px solid #333",
    },
  },
  {
    id: 2,
    name: "Triangle Down",
    number: "#2",
    style: {
      width: "0",
      height: "0",
      borderLeft: "25px solid transparent",
      borderRight: "25px solid transparent",
      borderTop: "50px solid #333",
    },
  },
  {
    id: 3,
    name: "Triangle Left",
    number: "#3",
    style: {
      width: "0",
      height: "0",
      borderTop: "25px solid transparent",
      borderRight: "50px solid #333",
      borderBottom: "25px solid transparent",
    },
  },
  {
    id: 4,
    name: "Triangle Right",
    number: "#4",
    style: {
      width: "0",
      height: "0",
      borderTop: "25px solid transparent",
      borderLeft: "50px solid #333",
      borderBottom: "25px solid transparent",
    },
  },
  {
    id: 5,
    name: "Arrow Up",
    number: "#5",
    style: {
      width: "33px",
      height: "33px",
      border: "2px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(225deg)",
    },
  },
  {
    id: 6,
    name: "Arrow Down",
    number: "#6",
    style: {
      width: "33px",
      height: "33px",
      border: "2px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(45deg)",
    },
  },
  {
    id: 7,
    name: "Arrow Left",
    number: "#7",
    style: {
      width: "33px",
      height: "33px",
      border: "2px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(135deg)",
    },
  },
  {
    id: 8,
    name: "Arrow Right",
    number: "#8",
    style: {
      width: "33px",
      height: "33px",
      border: "2px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(315deg)",
    },
  },
  {
    id: 9,
    name: "Thick Arrow Up",
    number: "#9",
    style: {
      width: "25px",
      height: "25px",
      border: "7px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(225deg)",
    },
  },
  {
    id: 10,
    name: "Thick Arrow Down",
    number: "#10",
    style: {
      width: "25px",
      height: "25px",
      border: "7px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(45deg)",
    },
  },
  {
    id: 11,
    name: "Thick Arrow Left",
    number: "#11",
    style: {
      width: "25px",
      height: "25px",
      border: "7px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(135deg)",
    },
  },
  {
    id: 12,
    name: "Thick Arrow Right",
    number: "#12",
    style: {
      width: "25px",
      height: "25px",
      border: "7px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(315deg)",
    },
  },

  {
    id: 13,
    name: "Check Mark",
    number: "#13",
    style: {
      width: "19px",
      height: "33px",
      border: "2px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(45deg)",
    },
  },
  {
    id: 14,
    name: "Thick Check Mark",
    number: "#14",
    style: {
      width: "19px",
      height: "33px",
      border: "10px solid #333",
      borderLeft: "0",
      borderTop: "0",
      transform: "rotate(45deg)",
    },
  },
  {
    id: 15,
    name: "Oval",
    number: "#15",
    style: {
      width: "50px",
      height: "38px",
      borderRadius: "50%",
      background: "#333",
    },
  },
  {
    id: 16,
    name: "Moon",
    number: "#16",
    style: {
      width: "50px",
      height: "50px",
      borderRadius: "50%",
      boxShadow: "9px 9px 0 0 #333",
      marginLeft: "-25px",
      marginTop: "-25px",
    },
  },
  {
    id: 17,
    name: "Triangle Top Left",
    number: "#17",
    style: {
      width: "0",
      height: "0",
      borderTop: "50px solid #333",
      borderRight: "50px solid transparent",
    },
  },
  {
    id: 18,
    name: "Triangle Top Right",
    number: "#18",
    style: {
      width: "0",
      height: "0",
      borderTop: "50px solid #333",
      borderLeft: "50px solid transparent",
    },
  },
  {
    id: 19,
    name: "Triangle Bottom Left",
    number: "#19",
    style: {
      width: "0",
      height: "0",
      borderBottom: "50px solid #333",
      borderRight: "50px solid transparent",
    },
  },
  {
    id: 20,
    name: "Triangle Bottom Right",
    number: "#20",
    style: {
      width: "0",
      height: "0",
      borderBottom: "50px solid #333",
      borderLeft: "50px solid transparent",
    },
  },
  {
    id: 21,
    name: "Trapezoid",
    number: "#21",
    style: {
      width: "40px",
      height: "0",
      borderBottom: "40px solid #333",
      borderLeft: "20px solid transparent",
      borderRight: "20px solid transparent",
    },
  },
  {
    id: 22,
    name: "Parallelogram",
    number: "#22",
    style: {
      width: "50px",
      height: "50px",
      background: "#333",
      transform: "skew(20deg)",
    },
  },

  {
    id: 23,
    name: "Egg",
    number: "#23",
    style: {
      width: "50px",
      height: "calc(50px * 1.44)",
      background: "#333",
      borderRadius: "50% 50% 50% 50% / 60% 60% 40% 40%",
    },
  },
];
export default shapesData;
